### ISSUE TITLE
minor issues during parsing compose

### ISSUE THREAD

**Issue by wey-gu** [glzjin/lzc-dtl#1]
- [ ] ports don't support `123` now only supports `123:123`
- [ ] commands don't accept list, only str is accepted
- [ ] entrypoint was ignored now, server-side evaluates it actually.

**Comment by glzjin** [comment]
Fixed, thanks.https://github.com/glzjin/lzc-dtl/commit/bac146fd071b6a2d9a1f2c1231bb730e8a00e1bc

**Comment by wey-gu** [comment]
OMG thanks 🧎🏻
